name: Publish Python Package

on:
  release:
    types: [created]
  # Allow manual triggers for testing the workflow
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install --no-interaction --with dev
    
    - name: Run tests
      run: poetry run pytest
    
    - name: Extract version from tag
      if: github.event_name == 'release'
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Update version in pyproject.toml if from tag
      if: github.event_name == 'release'
      run: poetry version ${{ steps.get_version.outputs.VERSION }}
    
    - name: Build package
      run: poetry build
    
    - name: Publish to PyPI
      if: github.event_name == 'release' && success()
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish